# Generated by Django 4.1.13 on 2023-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadd',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
